plugins {
	id 'fabric-loom' version '1.11.7'
}

loom {
	clientOnlyMinecraftJar()
	noIntermediateMappings()
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered {
		it.mappings("https://github.com/AntiquityMC/PotentialLamp/releases/download/${project.pl_mappings}/obfToNamed.jar")
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}

tasks.withType(JavaCompile).configureEach {
	// Minecraft 0.30 uses Java 5, but we need Java 8 for Fabric.
	it.options.release = 8
}
